### ISSUE TITLE
Uses unsafe function versions.

### ISSUE THREAD

**Issue by apotheon** [grassator/bdd-for-c#15]
Is there a specific reason this project uses sprintf() and strcat() instead of snprintf() and strlcat()?

**Comment by grassator** [comment]
No particular reason except me being unfamiliar with them. If the functions are part of C99 standard, added safety would be a great change to make.

**Comment by apotheon** [comment]
I submitted [a PR to address this](https://github.com/grassator/bdd-for-c/pull/16).  I also included some notes in a comment on that PR, describing a reasonably easy way to check your function choices for known issues when writing C, in case that helps.

**Comment by apotheon** [comment]
I had some kind of failure of attention with the previous PR for this, and mis-specified buffer sizes in `snprintf()` and `strlcat()` calls.  I have a new PR that corrects that and slightly clarifies the interface for use of the `__bdd_snprintf__()` function that uses `snprintf()` (formerly `__bdd_sprintf__()`:

PR https://github.com/grassator/bdd-for-c/pull/17

**Comment by grassator** [comment]
Thanks!
