### ISSUE TITLE
Add dependencies section to readme

### ISSUE THREAD

**Issue by fotonmoton** [grassator/bdd-for-c#20]
I assume that you on mac, because when I try to compile my program with your header on Ubuntu  I got messages like:

```
bdd-for-c.h:36:10: fatal error: 'term.h'
      file not found
#include <term.h>
         ^~~~~~~~
1 error generated.
```

and:

```
bdd-for-c.h:149:5: error: implicit
      declaration of function 'strlcat' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    strlcat(step->full_name, node->prefix, fullname_len);
    ^
```

To resolve first error, on Ubuntu-like distro, you need `libncurses5-dev` library.
For the second: `libbsd-dev`.

**Comment by grassator** [comment]
@fotonmoton Good catch, thanks. I added a section to the readme.
