### ISSUE TITLE
"realloc: invalid next size" in __bdd_format__

### ISSUE THREAD

**Issue by dscottboggs** [grassator/bdd-for-c#22]
I'm just learning C and have been using this very nice library to test my learning projects, so I thought for sure this was a bug in my code -- and it still might be, so sorry if it is. But when I try to run my specs, it exits with `realloc(): invalid next size`, at [this line](https://github.com/grassator/bdd-for-c/blob/434815d6987725ddbc1032618037c489dec1bf69/bdd-for-c.h#L366). I debugged it some, and found this possibly helpful information:

```
(lldb) n
Process 22113 stopped
* thread #1, name = 'spec', stop reason = step over
    frame #0: 0x0000555555555f4b spec`__bdd_format__(format="stackPop(data) == i") at bdd-for-c.h:366:30
   363      vsnprintf(result, size - 1, format, va);
   364 
   365      // Then clip to an actual size
-> 366      result = realloc(result, strlen(result) + 1);
   367 
   368      va_end(va);
   369      return result;
(lldb) print (size_t)strlen(result)
(size_t) $7 = 19
(lldb) print result
(char *) $8 = 0x0000555555564500 "stackPop(data) == i"
(lldb) n
realloc(): invalid next size
Process 22113 stopped
* thread #1, name = 'spec', stop reason = signal SIGABRT
    frame #0: 0x00007ffff7bf0d7f libc.so.6`__GI_raise + 271
libc.so.6`__GI_raise:
->  0x7ffff7bf0d7f <+271>: movq   0x108(%rsp), %rcx
    0x7ffff7bf0d87 <+279>: xorq   %fs:0x28, %rcx
    0x7ffff7bf0d90 <+288>: movl   %r8d, %eax
    0x7ffff7bf0d93 <+291>: jne    0x7ffff7bf0dae            ; <+318>
```

So it's not like the "next size" here is a negative number or huge or anything. That's about as far as I can figure out with this, will be curious to see what the issue is.

Thanks again for the great testing library :)

**Comment by grassator** [comment]
Thank you for the report. Could you please provide a minimal reproducible code if you can or full example if you can’t and also version of the compiler together with the platform and the flags / command used to compile?

**Comment by dscottboggs** [comment]
Sure, I meant to get you the code earlier and it just slipped my mind. [This](https://gist.github.com/dscottboggs/321615ae50bdb0c8fd8c5559f6da7b26) is the full text I'm working with, the error occurs in the *brainfuck/stack data/expands when its max-size is reached* spec, at the `check(stackPop...` line. The command I'm running to compile it is `cc -g brainfuckSpec.c -ospec -lbsd && ./spec`. `cc --version` outputs: `cc (GCC) 8.2.1 20181127`

I'll try to come up with a reduced example tonight or tomorrow.

**Comment by apotheon** [comment]
I've only skimmed so far, but one thing that jumps out at me in your code is line 61, where the for loop test is `i >= 0`.  The first loop counts 1-9, but this results in the second counting 9-0.  Should that read `i > 0` instead, to count 9-1?  (I'm not sure off the top of my head what I should expect to happen if you try to `realloc()` to size 0.)

EDIT: If that doesn't address your problem, it might also be helpful to include source for `stackPush()` and `stackPop()`.

**Comment by dscottboggs** [comment]
`stackPop()` never calls `realloc`, only `stackPush()`. The full source is at the gist link, not just the specs. `stackPush()` is at line 142.

**Comment by dscottboggs** [comment]
After further investigation, it seems like this is just some weird quirks that sometimes happen when a spec fails. Splitting specs/data structures into multiple files seems to help clear it up and get more helpful failure messages. It's kinda disappointing, but like, C macros are hard, I don't blame the project for having quirks. And again, the issue seems to go away if you use the project *as recommended* and split your specs into one file per spec.
