### ISSUE TITLE
Check vs Require

### ISSUE THREAD

**Issue by JKTKops** [grassator/bdd-for-c#27]
One very useful feature of Catch2 for C++ is the difference between the CHECK and REQUIRE macros. Specifically:
```cpp
GIVEN("an empty vector) {
  vector<int> test_vector;

  WHEN("1 is inserted) {
    test_vector.push_back(1);
    REQUIRE(test_vector.size() == 1);
    THEN("we can get and modify a reference to it") {
      CHECK(test_vector[0] == 1);
      test_vector[0] = 5;
      CHECK(test_vector[0] == 5);
    }
  }
}
```
This is a somewhat contrived example but the key is that if the REQUIRE fails, we know that we have a problem with push_back and there is no point in running the rest of the tests in this block since we depend on push_back. On the other hand, inside the THEN block, we want to run as many checks as possible. When it makes sense, we want checks to not fail-fast out of the block.

We can emulate the behavior of Catch's check by using a distinct `it` for each check. But as far as I can tell, there is no way to make a check fail out of the entire context, only the nearest enclosing `it`. Since bdd-for-c will crash if there is a segfault somewhere, it seems _extremely_ useful to be able to detect that we shouldn't even attempt the rest of the context.

If this isn't currently possible, I might be willing to take a stab at it.

**Comment by grassator** [comment]
Thank you for creating the issue. If I'm understanding correctly, believe you could emulate this behavior by using `before_each`:

```c
spec("some feature") {
    static int* array;

    before_each() {
        array = malloc(sizeof(int) * 10);
        // check that adding an element works:
        push_back(array, 1);
    }
    after_each() {
        free(array);
    }
    it ("can be modified and referenced") {
        check(array[0] == 1);
        array[0] = 5;
        check(array[0] == 5); 
    }
}
```
Does this match your expectations or you would expect something else?

**Comment by grassator** [comment]
Closed due to inactivity
