### ISSUE TITLE
Investigate `check` condition parsing.

### ISSUE THREAD

**Issue by grassator** [grassator/bdd-for-c#5]
Since most condition expressions in `check` are quite simple, it might be possible to try to parse them and output better assertion message.

As an alternative it might be better to provide something like `check_int_equal`, `check_string_equal` and in case of support for C11, generic macros `check_equal` and `check_not_equal` can be created.

**Comment by apotheon** [comment]
I'm not entirely clear on what you describe here.  Can you clarify, in case I feel like trying to take this on?

Also, if you're talking about *only* supporting C11, I'd suggest not doing so.  I wouldn't be able to use it for my projects, then, and many others might have the same problem.

**Comment by grassator** [comment]
@apotheon my idea was to support something like this:
https://github.com/power-assert-js/power-assert

It might be nice to write:

```c
assert(x > 0)
```

And get the error:

```
Expected x to be more than 0
```

But in all honesty I have no idea if it is worth it in terms of library complexity and compilation time. Also no idea if that is even something users would want to have.

**Comment by apotheon** [comment]
Got it.  Thanks.  I'll come back to this later and ponder what I would like, as a bdd-for-c user, and perhaps continue this discussion then.

**Comment by grassator** [comment]
After using the library for a while seems to be not worth it in real world

**Comment by apotheon** [comment]
Yeah, sorry, I didn't get back to this discussion.  Looking at it now, it does seem like this may not have been a very high-value change.

Thanks for your work on bdd-for-c.  I still haven't found a C testing library I like more for my small projects.
