### ISSUE TITLE
Example group implementation

### ISSUE THREAD

**Issue by Genaina** [grassator/bdd-for-c#9]
Hi folks,

First of all, thanks for the excellent implementation of Spec like tests for C! I wonder if you have in mind the implementation of example group using contexts in the same way as the [RSpec style](http://rspec.info/documentation/3.6/rspec-core/). To better illustrate, consider the following excerpt from the provided link:

        RSpec.describe "Using an array as a stack" do

        context "after an item has been pushed" do
            before(:example) do
                @stack.push :item
            end

            it 'allows the pushed item to be popped' do
                expect(@stack.pop).to eq(:item)
            end
        end
        end

Under the covers, this is (roughly) equivalent to:

    class UsingAnArrayAsAStack < RSpec::Core::ExampleGroup
  
    class AfterAnItemHasBeenPushed < self
        def before_example_2
          @stack.push :item
        end

        def it_allows_the_pushed_item_to_be_popped
            expect(@stack.pop).to eq(:item)
        end
    end
    end

The block is evaluated in the context of a subclass of RSpec::Core::ExampleGroup, or a subclass of the parent example group when you're nesting them.

**Comment by grassator** [comment]
@Genaina Thank you for creating an issue. Nested describes and context is indeed something that would be very beneficial. Existing implementation can't really handle this correctly and it looks like this is not an easy change.

Currently I'm looking into other ways I could structure the internals and will let you know the results.

**Comment by Genaina** [comment]
Is it due to the fact C is not object oriented?  Anyway, thank you for the update!

**Comment by grassator** [comment]
I'm not sure if you looked into how this is actually implemented, but the problem is that in C you can only define function at the top level (at least if we are talking about ANSI C without any extensions).

If it was possible to use lambdas, like in C++11, or indeed define function inside other functions (even without scope capture) this would all be much more straightforward.

**Comment by Genaina** [comment]
Indeed! This is was the problem why the other CSpec github project I tried did not work. My gcc compiler did not accept such construction....

**Comment by grassator** [comment]
I was able to implement nested `describe` and `context` statements and pushed update to master. You can take a look at [example.c](https://github.com/grassator/bdd-for-c/blob/master/example.c) for more details.

Please try it out and let me know if you experience any problems.

**Comment by Genaina** [comment]
Hi Dmitriy,

I tested it and it works perfectly!

Just a tiny minor comment. When you run with -Wall two warning messages pop
out: one for unused variable '__bdd_ignore_child__' and a similar one for
'__bdd_ignore_stack__' in lines 533 and 534 in bdd-for-c.h.

Thank you for your prompt solution!

-- Genaína.
<http://www.cic.unb.br/%7Egenaina/>

**Comment by grassator** [comment]
@Genaina I've fixed the warnings in the current master

**Comment by Genaina** [comment]
Great job!
